<a href="https://colab.research.google.com/github/blbt123/TIS/blob/main/2023_02_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
l = [1, 2, 3]
print(l)

l2 = [1, "a", [1,2,3]]
print(l2)

[1, 2, 3]
[1, 'a', [1, 2, 3]]


In [20]:
import numpy as np
arr = np.array([1,2,3,4])
arr1 = np.array([1,2,3,4.0])
arr2 = np.array([1,2,3,"4.0"])

In [21]:
print(type(arr))
print(type(arr1))
print(type(arr2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [22]:
print(arr, arr.dtype)
print(arr1, arr1.dtype)
print(arr2, arr2.dtype)

[1 2 3 4] int64
[1. 2. 3. 4.] float64
['1' '2' '3' '4.0'] <U21


In [26]:
arr3 = np.array([1,2,3,4])
print(arr3)

arr4 = np.array([[1,2,3],[4,5,6]])
print(arr4)

arr5 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr5)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
arr1 = np.array([1, 2, 3]) # 1차원, 백터형태
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # 2차원, 행렬형태
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3차원

# 형태(shape)확인
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

# 차원(dimension)확인
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

(3,)
(2, 3)
(2, 2, 2)
1
2
3


In [34]:
# 1.크기가 (4)인 1차원 넘파이 배열을 생성하고 차원 및 형태를 출력해 보세요 
# 2.크기가 (4,3)인 2차원 넘파이 배열을 생성하고 차원 및 형태를 출력해 보세요

arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print("1번 답")
print(arr1.shape)
print(arr1.ndim)

print("2번 답")
print(arr2.shape)
print(arr2.ndim)

# 강사님 답

# a = np.array([100,200,300,400])
# arr1 = np.array(a)
# print(arr1.shape)
# print(arr1.ndim)

# b = np.array([[100,200,300],[400,500,600],[700,800,900],[1000,1100,1200]])
# arr2 = np.array(b)
# print("2번 답")
# print(arr2.shape)
# print(arr2.ndim)

display(arr2) # 프린트보다 좀더 깔끔

1번 답
(4,)
1
2번 답
(4, 3)
2


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [38]:
a = list(range(10))

print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [40]:
arr1 = np.arange(5)
arr2 = np.arange(0,5,1)
display(arr1)
display(arr2)

array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [42]:
arr3 = np.arange(-1, 4.5, 1.5)
display(arr3)

array([-1. ,  0.5,  2. ,  3.5])

In [45]:
arr4 = np.arange(10, 1, -1)
arr4

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [46]:
arr5 = np.linspace(0,1,11)
arr5

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [48]:
z1 = np.zeros(5)
z1

array([0., 0., 0., 0., 0.])

In [53]:
z2 = np.zeros((3,2))
z2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [56]:
z3 = np.zeros((3,2,4))
display(z3)
print(z3.ndim)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

3


In [59]:
z4 = np.zeros((2,2), dtype = bool)
z4

array([[False, False],
       [False, False]])

In [60]:
z5 = np.ones((2,2), dtype = bool)
z5

array([[ True,  True],
       [ True,  True]])

In [63]:
c = np.ones((5,2), dtype = "i") # 정확한 i의 표현은 int32 
c

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [66]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [68]:
f = np.ones_like(b, dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [80]:
# 연습문제
# 1. 5크기의 전부 0과 전부 1로 채워진 넘파이 배열을 생성하시오

print("1번답")
z1 = np.zeros(5)
o1 = np.ones(5)

display(z1)
display(o1)

# 2. (3,4)크기의 전부 0과 전부 1로 채워진 넘파이 배열을 생성하고, 차원과 크기를 출력해 보세요.

print("\n2번답")
z2 = np.zeros((3,4))
o2 = np.ones((3,4))

display(z2)
display(o2)
print(z2.ndim,z2.shape)
print(o2.ndim,o2.shape)

# 3. 다음 배열(arr1)과 같은 크기를 같으며, 각각 0과 1로만 채워진 두개의 배열을 생성해 보세요

arr1 = np.array([[1,2,3],[4,5,6]])
z3 = np.zeros_like(arr1)
o3 = np.ones_like(arr1)

print("\n3번답")
display(z3)
display(o3)
# 4. 다음 배열(arr2)과 같은 크기를 같으며, 각각 0과 1로만 채워진 두개의 배열을 생성해 보세요

arr2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
z4 = np.zeros_like(arr2)
o4 = np.ones_like(arr2)

print("\n4번답")
display(z4)
display(o4)

1번답


array([0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1.])


2번답


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

2 (3, 4)
2 (3, 4)

3번답


array([[0, 0, 0],
       [0, 0, 0]])

array([[1, 1, 1],
       [1, 1, 1]])


4번답


array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [82]:
arr1 = np.random.normal(0, 1, 5)
arr2 = np.random.normal(10, 3, (3, 3))

print(arr1)
print(arr2)

[ 1.68254283 -1.09775148  0.69811483  0.14151048 -1.70913542]
[[ 8.04106838 10.1607293   8.52514529]
 [10.21308558 13.74648216 12.70014907]
 [ 5.26746878  9.82423297 13.96656932]]


In [87]:
# 1. 요소개수가 7개이고, 평균이 0, 분산이 1인 난수 넘파이 배열을 생성하세요.

ran = np.random.normal(0, 1, 7)

print("1")
print(ran)

# 2. 다음 배열과 같은 크기의 평균 3, 분산 2인 난수 넘파이 배열을 생성하세요.
arr = np.zeros((3,2)) 

print("\n2")
print(np.random.normal(3, 2, arr.shape))

1
[ 0.38494116  0.16971654 -0.70254198  0.78961102 -1.85779675  0.41705103
  0.82464851]

2
[[1.3244077  3.96960961]
 [4.57409102 5.79699769]
 [4.42152222 0.73731037]]


In [90]:
# 난수 시드 설정
np.random.seed(42)

# 0과 1사이의 5개의 요소로 구성된 배열 생성
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [91]:
# np.random.shuffle()

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.random.shuffle(x)
x

array([0, 1, 8, 5, 3, 4, 7, 9, 6, 2])

In [93]:
np.random.choice(x, 2,True, None)

array([3, 1])

In [102]:
# '오늘 뭐 먹지?' 라는 모바일 앱을 만드려고 해요
menu = ['라면', '스파게티', '된장찌개', '파전']

menu_arr = np.array(menu)
recommended_menu = np.random.choice(menu_arr, 1, replace=True, p=[0.1, 0.1, 0.1, 0.7])
recommended_menu

array(['파전'], dtype='<U4')

In [104]:
# raand: 0부터 1사이의 균일 분포
np.random.rand(10)

array([0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
       0.36636184, 0.45606998, 0.78517596, 0.19967378, 0.51423444])

In [105]:
# randn 표준 정규 분포(평균:0, 분산, 1)
np.random.randn(10)

array([-0.54438272,  0.11092259, -1.15099358,  0.37569802, -0.60063869,
       -0.29169375, -0.60170661,  1.85227818, -0.01349722, -1.05771093])

In [106]:
# randint: 균일 분포의 정수 난수

# 로또 번호 생성기(1~45의 숫자 중에서 7개의 임의의 숫자 추출)

np.random.randint(45, size=7)

array([34, 13, 16, 35, 39,  3,  1])

In [114]:
np.random.seed(0)

np.random.randint(45, size=7)

array([44,  0,  3,  3, 39,  9, 19])

In [118]:
arr1 = np.array([1, 2, 3, 4, 5, 6])

print(arr1.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [128]:
arr1 = np.zeros((4,3))
print(arr1)
arr2 = arr1.reshape(2,6)
print("="*30)
print(arr2)
arr3 = arr1.reshape(2,3,2)
print("="*30)
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [130]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1.reshape(3, 2)) # (3,2)로 구조 변경
print("="*30)
print(arr2.reshape(-1, 2))  # 열 개수를 2개로 구조 변경, -1은 알아서 들어가게끔 하는 코드, (3,2) -> (-1,2)
print("="*30)
print(arr1.reshape(-1, 1))  # 열 개수를 1개로 구조 변경, (6,) -> (6,1)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [147]:
# 연습문제
# 1. 다음 배열이 주어졌을 때, 이 배열과 구성요소가 같고 크기만 (3,8)로 다른 2차원 배열을 생성하시오.

arr = np.arange(24)
print(arr.reshape(3,8))
# arr2 = arr.reshape(3,8)
# print(arr2)

# 2. 위 배열을(6,4) 크기의 배열로 만들되, reshape() 메서드에서 -1을 첫번째 인자로 활용하세요

print("="*30)
print(arr.reshape(-1,2))
# arr3 = arr.reshape(-1,4)
# print(arr3)

# 3. 위 배열을 (3,4,2) 크기의 배열로 만들되, reshape() 메서드에서 -1을 두 번째 인자로 활용하세요
# 그리고 원하는 형태로 잘 변형되었는지를 확인해 보세요 (shape속성 활용)

print("="*30)
arr2 = arr.reshape(3,4,2)
print(arr2)
# arr4 = arr.reshape(3,4,2)
# print(arr4)
print(arr2.shape)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
(3, 4, 2)


In [148]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a + b

array([5, 7, 9])

In [149]:
x1 = np.random.random(10 ** 6) # 100만 개의 난수로 구성된 배열 생성
x2 = np.random.random(10 ** 6)

In [151]:
%%timeit
s = x1 + x2

1.92 ms ± 51.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [152]:
%%timeit
s = []

for e1, e2 in zip(x1, x2):
  s.append(e1 + e2)

303 ms ± 143 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## %%time
한번만 실행하면서 수행 시간을 확인하는 방법,  
너무 간단한 함수는 한 번만 수행하기 때문에 수행 시간이 너무 짧게 나올 수 있다.


## %%timeit
timeit 여러번 반복해서 코드를 수행하면서 평균과 표준편차를 구해서 더욱 정밀하게 시간을 측정할 수 있다.

옵션

- -r : 몇 loop를 돌 것인지 설정

- -n : 각 loop당 몇 번 실행할 것인지 설정

In [165]:
%%time
# 연습문제
# 1. 1-100까지 1씩 증가하는 원소(요소)로 구성된 넘파이 배열이 있다. 각각의 요소에 3제곱한 새로운 배열을 생성하시오
x = np.arange(1, 101)
print("x ** 3 = ", x**3)
# 2. 각각의 요소를 제곱근을 취한 새로운 배열을 생성하시오.(힌트:np.sqrt)
print("x의 제곱근 = ", np.sqrt(x))
# 3. 각각의 원소에 10을 더한 새로운 배열 생성하시오.
print("x + 10 = ", x+10)

x ** 3 =  [      1       8      27      64     125     216     343     512     729
    1000    1331    1728    2197    2744    3375    4096    4913    5832
    6859    8000    9261   10648   12167   13824   15625   17576   19683
   21952   24389   27000   29791   32768   35937   39304   42875   46656
   50653   54872   59319   64000   68921   74088   79507   85184   91125
   97336  103823  110592  117649  125000  132651  140608  148877  157464
  166375  175616  185193  195112  205379  216000  226981  238328  250047
  262144  274625  287496  300763  314432  328509  343000  357911  373248
  389017  405224  421875  438976  456533  474552  493039  512000  531441
  551368  571787  592704  614125  636056  658503  681472  704969  729000
  753571  778688  804357  830584  857375  884736  912673  941192  970299
 1000000]
x의 제곱근 =  [ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974
  2.64575131  2.82842712  3.          3.16227766  3.31662479  3.46410162
  3.60555128  3.74165

In [192]:

# 연습
# 각각의 배열의 각각의 원소에 3을 곱하고 1을 뺀 함수를 구현하여 적용하시오
arr = np.arange(10)

def plus_three_minus_one(x):
   return x*3-1
print(plus_three_minus_one(arr))

[-1  2  5  8 11 14 17 20 23 26]


In [182]:
x = np.array([1,2,3])
y = np.array([1,3,-2])

print(x >= 2)

[False  True  True]


In [197]:
# 연습문제
# 다음 배열에서 짝수인 요소의 개수를 출력하는 코드를 작성하시오
arr = np.arange(45)

# 긴버전
cond = arr%2 ==0
# print(cond)
print(sum(cond))
# 짧은 버전
print(sum(arr % 2 ==0 ))


23
23


In [200]:
a = np.array([[1,2], [3,4]]) # (2,2)의 2차원 배열, 즉 행렬
b = np.array([-1, -2]) # (2,)의 1차월 배열, 백터
print(a, "\n")
print(b, "\n")
print(a + b)

[[1 2]
 [3 4]] 

[-1 -2] 

[[0 0]
 [2 2]]


In [202]:
  import numpy as np
x = np.arange(15).reshape(5, 3) # method chaining (함수를 연결해서 사용)
display(x)  # display 함수를 사용하여 x의 원 구조를 망가트리지 않고 출력

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [205]:
# sum은 함수 형태 및 메서드 형태 모두 지원 # axis함수 할 차례

print(np.sum(x))
print(x.sum())

105
105
